name: Test

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create test file
        run: echo "$RANDOM" > test-file
      - name: Cache test file
        uses: actions/cache@v4
        with:
          path: test-file
          key: ${{ runner.os }}-${{ github.run_id }}-test-file

  cache-hit-key:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore test file
        uses: actions/cache@v4
        id: cache
        with:
          path: test-file
          key: ${{ runner.os }}-${{ github.run_id }}-test-file
      - name: Check outputs
        run: printf 'cache-hit (with square brackets) is [%s]' "${{ steps.cache.outputs.cache-hit }}"

  cache-hit-restore-keys:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore test file
        uses: actions/cache@v4
        id: cache
        with:
          path: test-file
          key: ${{ runner.os }}-${{ github.run_id }}-test-file-xxx
          restore-keys: ${{ runner.os }}-${{ github.run_id }}-test-
      - name: Check outputs
        run: printf 'cache-hit (with square brackets) is [%s]' "${{ steps.cache.outputs.cache-hit }}"

  cache-miss:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore test file
        uses: actions/cache@v4
        id: cache
        with:
          path: test-file
          key: ${{ runner.os }}-${{ github.run_id }}-test-file-yyy
      - name: Check outputs
        run: printf 'cache-hit (with square brackets) is [%s]' "${{ steps.cache.outputs.cache-hit }}"

  cache-hit-key-prefix:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore test file
        uses: actions/cache@v4
        id: cache
        with:
          path: test-file
          key: ${{ runner.os }}-${{ github.run_id }}-test-
      - name: Check outputs
        run: printf 'cache-hit (with square brackets) is [%s]' "${{ steps.cache.outputs.cache-hit }}"
